### ISSUE TITLE
I have a problem with learn function. May it can help you.

### ISSUE THREAD

**Issue by dds0117** [Abdelhamid-bouzid/Monte-carlo-deep-reinforcement-learning-#1]
I think your reward is wrong. Your new_reward is like Q-value, however qt+1= new_reward + thet * qt instead of qt+1 = reward + thet* qt.

**Comment by Abdelhamid-bouzid** [comment]
@dds0117  Thank you so much for the comment

I think the state value is correct (it is the new reward). In the function "play_episode", we are storing the episode history in this order:  
  - current state, action, new state and the reward in the new state. 
  Then in the loop (shown below), for the current state (Qt =  reward_from_new state + self.gamma * Q_t+1). You can check that by running the code in debug mode. 
        R = 0
        new_rewards = rewards
        for i in range(len(rewards)-1, -1, -1):
            R = (rewards[i] + self.gamma * R)
            new_rewards[i] = R

**Comment by dds0117** [comment]
OK，I understand the new reward likes the Q value，and you use it as reward.&nbsp; Therefore, you use monte carlo method.&nbsp;



---Original---
From: "Abdelhamid ***@***.***&gt;
Date: Fri, Apr 23, 2021 17:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Abdelhamid-bouzid/Monte-carlo-deep-reinforcement-learning-] I have a problem with learn function. May it can help you. (#1)




 
@dds0117  Thank you so much for the comment
 
I think the state value is correct (it is the new reward). In the function "play_episode", we are storing the episode history in this order:
  
current state, action, new state and the reward in the new state.
 Then in the loop (shown below), for the current state (Qt =  reward_from_new state + self.gamma * Q_t+1). You can check that by running the code in debug mode.
 R = 0
 new_rewards = rewards
 for i in range(len(rewards)-1, -1, -1):
 R = (rewards[i] + self.gamma * R)
 new_rewards[i] = R

**Comment by Abdelhamid-bouzid** [comment]
Exactly. Thank you for your comment.

**Comment by dds0117** [comment]
I understand. Cool! Thank you!



---Original---
From: "Abdelhamid ***@***.***&gt;
Date: Fri, Apr 23, 2021 18:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Abdelhamid-bouzid/Monte-carlo-deep-reinforcement-learning-] I have a problem with learn function. May it can help you. (#1)




 
Exactly. Thank you for your comment.
